config/routes.rb
Rails.application.routes.draw do

  root 'forums#index'

  devise_for :users, controllers: {registrations: "registrations" }

  resources :comments
  resources :courses
  resources :forums
  resources :posts
  resources :users

  get 'comments/new/:id', controller: 'comments', action: 'new'
  get 'courses/new/:id',  controller: 'courses',  action: 'new'
  get 'posts/new/:id',    controller: 'posts',    action: 'new'

end

app/models/forum.rb
class Forum < ApplicationRecord

  # relacionamentos
  has_many :courses

  # validações
  validates :title, presence: true, uniqueness: true, length: {minimum: 3}

end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :authenticate_user!, only: [:new,  :edit, :create, :update, :destroy]
  before_action :set_forum,          only: [:show, :edit, :update, :destroy]

  def index
    @forums = Forum.all.sort_by{ |item| item[:title] }
    # guardará o post mais recente de um curso
    @post = nil
  end

  def new
    @forum = Forum.new
  end

  def show
  end

  def edit
  end

  def create
    @forum = Forum.new(forum_params)
    respond_to do |format|
      if @forum.save
        format.html { redirect_to root_path, notice: t(:forum_created) }
        format.json { render :show, status: :created, location: @forum }
      else
        format.html { render :new }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @forum.update(forum_params)
        format.html { redirect_to root_path, notice: t(:forum_updated) }
        format.json { render :show, status: :ok, location: @forum }
      else
        format.html { render :edit }
        format.json { render json: @forum.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # apaga todos os cursos antes
    @forum.courses.each do |course|
      course.destroy
    end
    # apaga o fórum
    @forum.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: t(:forum_destroyed) }
      format.json { head :no_content }
    end
  end

  private

  def set_forum
    @forum = Forum.find(params[:id])
  end

  def forum_params
    params.require(:forum).permit(:title, :description)
  end

end

app/helpers/forums_helper.rb
module ForumsHelper

  # grava em @post o último post de um curso
  def last_post course
    if course.posts.size > 0
      @post = posts_of(course).first
    else
      @post = nil
    end
  end

  def new_course forum
    "#{new_course_path}/#{forum.id}"
  end

  def number_of_posts course
    course.posts.size
  end
  
  def number_of_messages course
    count = number_of_posts course
    course.posts.each do |post|
      count += post.comments.size
    end
    count
  end
  
  def courses_of forum
    forum.courses.sort_by{ |item| item[:title] }
  end
  
  def number_of_all_messages
    "#{Comment.all.size + Post.all.size}"
  end
  
  def number_of_users
    "#{User.all.size}"
  end
  
  def last_user_name
    if User.all.size > 0
      User.last.name
    else
      "Indefinido"
    end
  end

end

app/views/forums/_form.html.erb
<%= form_with(model: forum, local: true) do |form| %>
  <% if forum.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(forum.errors.count, "error") %> prohibited this forum from being saved:
      </h2>
      <ul>
        <% forum.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label t(:title) %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label t(:description) %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/forums/edit.html.erb
<% if current_user.admin? %>
  <title><%= t(:editing_forum) %></title>
  <h3><%= t(:editing_forum) %></h3>
  <%= render 'form', forum: @forum %>
  <%= link_to t(:back), root_path, :class => 'btn btn-default btn-xs' %>
<% else %>
  <title><%= t(:forbidden) %></title>
  <h1><%= t(:forbidden) %></h1>
<% end %>

app/views/forums/index.html.erb
<title><%= t(:forum_title) %></title>
<% @forums.each do |forum| %>
  <hr>
  <h3><%= forum.title %></h3>
  <% if user_signed_in? && current_user.admin? %>
    <div>
      <%= link_to t(:new_course), new_course(forum), :class => 'btn btn-default btn-xs' %>
      <%= link_to t(:edit), edit_forum_path(forum), :class => 'btn btn-default btn-xs' %>
      <%= link_to t(:delete), forum, method: :delete, data: { confirm: t(:are_you_sure) }, :class => 'btn btn-xs btn-danger' %>
    </div>
  <% end %>
  <% if forum.courses.size > 0 %>
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= t(:course_name) %></th>
          <th><%= t(:posts) %></th>
          <th><%= t(:messages) %></th>
          <th><%= t(:last_message) %></th>
        </tr>
      </thead>
      <tbody>
        <% courses_of(forum).each do |course| %>
          <tr>
            <td width=60%>
              <% if user_signed_in? && current_user.admin? %>
                <%= link_to t(:edit), edit_course_path(course), :class => 'btn btn-default btn-xs' %>
                <%= link_to t(:delete), course, method: :delete, data: { confirm: t(:are_you_sure) }, :class => 'btn btn-xs btn-danger' %>
              <% end %>
              <%= link_to course.title, course %>
            </td>
            <td><%= number_of_posts course %></td>
            <td><%= number_of_messages course %></td>
            <td>
              <% last_post course %>
              <% if @post != nil %>
                <% if @post.comments.size > 0 %>
                  <% if @post.comments.last.user.admin? %>
                    <b><font color=blue><%= @post.comments.last.user.name %></font></b>
                  <% else %>
                    <b><%= @post.comments.last.user.name %></b>
                  <% end %>
                <% else %>
                  <% if @post.user.admin? %>
                    <b><font color=blue><%= @post.user.name %></font></b>
                  <% else %>
                    <b><%= @post.user.name %></b>
                  <% end %>
                <% end %>
                <br><%= "#{t(:in)} " %><%= link_to @post.title, @post %>
              <% else %>
                <%= t(:no_disponible) %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <h4><%= t(:dont_have_courses) %></h4>
  <% end %>
<% end %>

<hr>
<b><%= t(:statistics) %></b>
<br><%= "#{t(:we_members)} " %><b><%= number_of_all_messages %></b><%= " #{t(:messages_lo)}" %>
<br><%= "#{t(:have)} " %><b><%= number_of_users %></b><%= " #{t(:registered_users)}" %>
<br><%= "#{t(:the_last_user)} " %><b><%= last_user_name %></b>

app/views/forums/new.html.erb
<% if current_user.admin? %>
  <title><%= t(:new_forum) %></title>
  <h3><%= t(:new_forum) %></h3>
  <%= render 'form', forum: @forum %>
  <%= link_to t(:back), root_path, :class => 'btn btn-default btn-xs' %>
<% else %>
  <title><%= t(:forbidden) %></title>
  <h1><%= t(:forbidden) %></h1>
<% end %>

app/views/forums/show.html.erb
<title><%= t(:resource_nd) %></title>
<h1><%= t(:resource_nd) %></h1>