config/routes.rb
Rails.application.routes.draw do

  root 'forums#index'

  devise_for :users, controllers: {registrations: "registrations" }

  resources :comments
  resources :courses
  resources :forums
  resources :posts
  resources :users

  get 'comments/new/:id', controller: 'comments', action: 'new'
  get 'courses/new/:id',  controller: 'courses',  action: 'new'
  get 'posts/new/:id',    controller: 'posts',    action: 'new'

end

app/models/post.rb
class Post < ApplicationRecord

  # imagem anexa
  has_attached_file :picture, :styles => { :medium => "500x500>", :big => "900x900>" }
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/

  # relacionamentos
  belongs_to :user
  belongs_to :course
  has_many   :comments, :dependent => :delete_all

  # validações
  validates :title,     presence: true, length: {minimum: 3}
  validates :content,   presence: true, length: {minimum: 3}
  validates :course_id, presence: true
  validates :user_id,   presence: true

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new,  :edit, :create, :update, :destroy]
  before_action :set_post,           only: [:show, :edit, :update, :destroy]

  def index
    # ransack
    @q = Post.ransack(params[:q])
    @posts = @q.result.sort_by{ |item| item[:title] }
  end

  def new
    @post = Post.new
    # id do curso que conterá o novo post
    @@course_id = params[:id].to_i
  end

  def show
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    # id do curso que contém o novo post
    @post.course_id = @@course_id
    # id do usuário que criou o post
    @post.user_id = current_user.id

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: t(:post_created) }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: t(:post_updated) }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to request.referrer, notice: t(:post_destroyed) }
      format.json { head :no_content }
    end
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :picture)
  end

end

app/helpers/posts_helper.rb
module PostsHelper

  def comments_of post
    post.comments.sort_by{ |item| item[:created_at] }
  end

  def new_comment post
    "#{new_comment_path}/#{post.id}"
  end

end

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:
      </h2>
      <ul>
        <% post.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label t(:title) %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label t(:message) %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label t(:img) %>
    <%= form.file_field :picture %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<% if current_user.id == @post.user_id %>
  <title><%= t(:editing_post) %></title>
  <h3><%= t(:editing_post) %></h3>
  <%= render 'form', post: @post %>
  <%= link_to t(:back), @post.course, :class => 'btn btn-default btn-xs' %>
<% else %>
  <title><%= t(:forbidden) %></title>
  <h1><%= t(:forbidden) %></h1>
<% end %>

app/views/posts/index.html.erb
<title><%= t(:search_posts) %></title>
<h3><%= t(:search_posts) %></h3>

<br>
<div align=left>
  <%= search_form_for @q do |f| %>
    <b><%= t(:cont_the_title) %></b>
    <%= f.search_field :title_cont %>
    <%= f.submit %>
  <% end %>
</div>
<br>

<% if @posts.size > 0 %>
  <table class="table table-striped">
    <thead>
      <th width=50%><%= t(:post_name) %></th>
      <th><%= t(:answers) %></th>
      <th><%= t(:created_by) %></th>
      <th><%= t(:course) %></th>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td>
            <% if user_signed_in? && (current_user.admin? || current_user.id == post.user.id) %>
              <% if current_user.id == post.user.id %>
                <%= link_to t(:edit), edit_post_path(post), :class => 'btn btn-default btn-xs' %>
              <% end %>
              <%= link_to t(:delete), post, method: :delete, data: { confirm: t(:are_you_sure) }, :class => 'btn btn-xs btn-danger' %>
            <% end %>
            <%= link_to post.title, post %>
          </td>
          <td><%= post.comments.size %></td>
          <td>
            <b>
              <% if post.user.admin? %>
                <font color=blue><%= post.user.name %></font>
              <% else %>
                <%= post.user.name %>
              <% end %>
            </b>
            <br><%= date(post.created_at) %>
          </td>
          <td><%= link_to post.course.title, post.course %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/posts/new.html.erb
<title><%= t(:new_post) %></title>
<h3><%= t(:new_post) %></h3>
<%= render 'form', post: @post %>
<%= link_to t(:back), "#{courses_path}/#{params[:id]}", :class => 'btn btn-default btn-xs' %>

app/views/posts/show.html.erb
<title><%= @post.title %></title>
<div>
  <h7>
    <%= link_to @post.course.forum.title, root_path %> ::
    <%= link_to @post.course.title, @post.course %> ::
    <%= link_to @post.title, @post %>
  </h7>
</div>
<h3><%= @post.title %></h3>
<% if user_signed_in? %>
  <p>
    <div>
      <% if current_user.id == @post.user.id %>
        <%= link_to t(:edit_post), edit_post_path(@post), :class => 'btn btn-default btn-xs' %>
      <% end %>
      <%= link_to t(:new_comment), new_comment(@post), :class => 'btn btn-default btn-xs' %>
    </div>
  </p>
<% end %>
<table class="table table-striped">
  <tr>
    <td width=20%>
      <center>
        <%= image_tag @post.user.avatar.url(:thumb) %>
        <br>
        <% if @post.user.admin? %>
          <b><font color=blue><%= @post.user.name %></font></b>
          <br><%= t(:admin) %>
        <% else %>
          <b><%= @post.user.name %></b>
          <br><%= t(:user) %>
        <% end %>
        <br><%= "#{t(:registered_at)} " %>
        <br><%= date(@post.user.created_at) %>
        <br><%= @post.user.comments.size %><%= " #{t(:comments_lo)}" %>
      </center>
    </td>
    <td>
      <p>
        <sup><%= "#{t(:in)} " %><%= date(@post.updated_at) %></sup>
        <div><%= markdown(@post.content) %></div>
      </p>
      <% if !@post.picture.blank? %>
        <%= image_tag @post.picture.url(:big) %>
      <% end %>
    </td>
  </tr>
  <% if @post.comments.size > 0 %>
    <% comments_of(@post).each do |comment| %>
      <tr>
        <td>
          <center>
            <%= image_tag comment.user.avatar.url(:thumb) %>
            <br>
            <% if comment.user.admin? %>
              <b><font color=blue><%= comment.user.name %></font></b>
              <br><%= t(:admin) %>
            <% else %>
              <b><%= comment.user.name %></b>
              <br><%= t(:user) %>
            <% end %>
            <br><%= "#{t(:registered_at)} " %>
            <br><%= date(comment.user.created_at) %>
            <br><%= comment.user.comments.size %><%= " #{t(:comments_lo)}" %>
          </center>
        </td>
        <td>
          <div>
            <% if user_signed_in? && (current_user.admin? || current_user.id == comment.user.id) %>
              <% if current_user.id == comment.user.id %>
                <%= link_to t(:edit), edit_comment_path(comment), :class => 'btn btn-default btn-xs' %>
              <% end %>
              <%= link_to t(:delete), comment, method: :delete, data: { confirm: t(:are_you_sure) }, :class => 'btn btn-danger btn-xs' %>
            <% end %>
          </div>
          <p>
            <sup><%= "#{t(:in)} " %><%= date(comment.updated_at) %></sup>
            <div><%= markdown(comment.content) %></div>
          </p>
          <% if !comment.picture.blank? %>
            <%= image_tag comment.picture.url(:medium) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  <% end %>
</table>