config/routes.rb
Rails.application.routes.draw do

  root 'forums#index'

  devise_for :users, controllers: {registrations: "registrations" }

  resources :comments
  resources :courses
  resources :forums
  resources :posts
  resources :users

  get 'comments/new/:id', controller: 'comments', action: 'new'
  get 'courses/new/:id',  controller: 'courses',  action: 'new'
  get 'posts/new/:id',    controller: 'posts',    action: 'new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div align=right>
      <p>
        <a href="http://www.usp.br" align=right>
          <img src=/usp.jpg width=5%>
        </a>
      </p>
    </div>
    <div class="navbar navbar-default navbar-static-top">
      <center>
        <%= link_to root_path do %>
          <%= image_tag root_url + "ime.png", size: "100x118", :alt => "Logo" %>
        <% end %>
        <h3>
          <b>
            <%= t(:institute) %>
            <br><%= t(:discussion) %>
          </b>
        </h3>
      </center>
    </div>
    <div align=right>
      <% if user_signed_in? %>
        <%= "#{t(:welcome)}, " %>
        <% if current_user.admin? %>
          <b><font color=blue><%= current_user.name %></font></b><%= "!" %>
          <%= link_to t(:new_forum), new_forum_path, :class => 'btn btn-default btn-xs' %>
          <%= link_to t(:control_users), users_path, :class => 'btn btn-default btn-xs' %>
        <% else %>
          <b><%= current_user.name %></b><%= "!" %>
        <% end %>
        <%= link_to t(:edit_data), edit_user_registration_path, :class => 'btn btn-default btn-xs' %>
        <%= link_to t(:logout), destroy_user_session_path, method: :delete, :class => 'btn btn-default btn-xs' %>
      <% else %>
        <%= t(:no_user_logged_msg) %>
        <%= link_to t(:new_user), new_user_registration_path, :class => 'btn btn-default btn-xs' %>
        <%= link_to t(:login), new_user_session_path, :class => 'btn btn-default btn-xs' %>
      <% end %>
      <p><%= link_to t(:search_posts), posts_path, :class => 'btn btn-default btn-xs' %></p>
    </div>
    <p id="notice"><%= notice %></p>
    <%= yield %>
  </body>
</html>